Imports System.Runtime.Serialization

Public Enum CurrencyCode
    <EnumMember(Value:="Canadian Dollar")> CAD
    <EnumMember(Value:="United States Dollar")> USD
    <EnumMember(Value:="Andorran Peseta")> ADP
    <EnumMember(Value:="United Arab Emirates Dirham")> AED
    <EnumMember(Value:="Afghani")> AFA
    <EnumMember(Value:="Afghani")> AFN
    <EnumMember(Value:="Lek")> ALL
    <EnumMember(Value:="Armenian Dram")> AMD
    <EnumMember(Value:="Netherlands Antillian Guilder")> ANG
    <EnumMember(Value:="Kwanza")> AOA
    <EnumMember(Value:="Kwanza")> AOK
    <EnumMember(Value:="New Kwanza")> AON
    <EnumMember(Value:="Argentine Peso")> ARP
    <EnumMember(Value:="Argentine Peso")> ARS
    <EnumMember(Value:="Schilling")> ATS
    <EnumMember(Value:="Australian Dollar")> AUD
    <EnumMember(Value:="Aruba Florin")> AWF
    <EnumMember(Value:="Aruban Guilder")> AWG
    <EnumMember(Value:="Azerbaijanian Manat")> AZM
    <EnumMember(Value:="Azerbaijan Manat")> AZN
    <EnumMember(Value:="Convertible Mark")> BAK
    <EnumMember(Value:="Convert. Marks (Bosnia/Herzegovina)")> BAM
    <EnumMember(Value:="Barbados Dollar")> BBD
    <EnumMember(Value:="Taka (Bangladesh)")> BDT
    <EnumMember(Value:="Belgian Franc (convertible)")> BEC
    <EnumMember(Value:="Belgian Franc")> BEF
    <EnumMember(Value:="Belgian Franc (financial)")> BEL
    <EnumMember(Value:="Lev")> BGL
    <EnumMember(Value:="Bulgarian Lev")> BGN
    <EnumMember(Value:="Bahraini Dinar")> BHD
    <EnumMember(Value:="Burundi Franc")> BIF
    <EnumMember(Value:="Bermudian Dollar")> BMD
    <EnumMember(Value:="Brunei Dollar")> BND
    <EnumMember(Value:="Boliviano")> BOB
    <EnumMember(Value:="Bolivian Peso")> BOP
    <EnumMember(Value:="Mvdol (Bolivia)")> BOV
    <EnumMember(Value:="Cruzeiro")> BRC
    <EnumMember(Value:="Brazilian Real")> BRL
    <EnumMember(Value:="Bahamian Dollar")> BSD
    <EnumMember(Value:="Ngultrum (Bhutan)")> BTN
    <EnumMember(Value:="Bhutan Rupee")> BTR
    <EnumMember(Value:="Kyat")> BUK
    <EnumMember(Value:="Pula (Botswana)")> BWP
    <EnumMember(Value:="Belarusian Ruble")> BYN
    <EnumMember(Value:="Belarusian Ruble")> BYR
    <EnumMember(Value:="Belize Dollar")> BZD
    <EnumMember(Value:="Congolese Franc")> CDF
    <EnumMember(Value:="New Zaire")> CDZ
    <EnumMember(Value:="WIR Euro (Suisse)")> CHE
    <EnumMember(Value:="Swiss Franc (Liechtenstein)")> CHF
    <EnumMember(Value:="WIR Franc Switzerland")> CHW
    <EnumMember(Value:="Unidades de Formento (Chile)")> CLF
    <EnumMember(Value:="Chilean Peso")> CLP
    <EnumMember(Value:="Yuan Renminbi (China)")> CNY
    <EnumMember(Value:="Colombian Peso")> COP
    <EnumMember(Value:="Unidad de Valor Real (Columbia)")> COU
    <EnumMember(Value:="Costa Rican Colon")> CRC
    <EnumMember(Value:="Serbian Dinar")> CSD
    <EnumMember(Value:="Koruna (Czechoslovakia)")> CSK
    <EnumMember(Value:="Peso Convertible")> CUC
    <EnumMember(Value:="Cuban Peso")> CUP
    <EnumMember(Value:="Cape Verde Escudo")> CVE
    <EnumMember(Value:="Cyprus Pound")> CYP
    <EnumMember(Value:="Czech Koruna")> CZK
    <EnumMember(Value:="Mark der DDR")> DDM
    <EnumMember(Value:="Deutsche Mark")> DEM
    <EnumMember(Value:="Djibouti Franc")> DJF
    <EnumMember(Value:="Danish Krone")> DKK
    <EnumMember(Value:="Dominican Peso")> DOP
    <EnumMember(Value:="Algerian Dinar")> DZD
    <EnumMember(Value:="Sucre")> ECS
    <EnumMember(Value:="Kroon (Estonia)")> EEK
    <EnumMember(Value:="Egyptian Pound")> EGP
    <EnumMember(Value:="Nakfa (Eritrea)")> ERN
    <EnumMember(Value:="Spanish Peseta")> ESP
    <EnumMember(Value:="Ethiopian Birr")> ETB
    <EnumMember(Value:="Euro")> EUR
    <EnumMember(Value:="Markka")> FIM
    <EnumMember(Value:="Fiji Dollar")> FJD
    <EnumMember(Value:="Falkland Islands Pound")> FKP
    <EnumMember(Value:="French Franc")> FRF
    <EnumMember(Value:="Pound Sterling (United Kingdom)")> GBP
    <EnumMember(Value:="Lari (Georgia)")> GEL
    <EnumMember(Value:="Cedi (Ghana)")> GHC
    <EnumMember(Value:="Cedi (Ghana)")> GHS
    <EnumMember(Value:="Gibraltar Pound")> GIP
    <EnumMember(Value:="Dalasi (Gambia)")> GMD
    <EnumMember(Value:="Guinean Franc")> GNF
    <EnumMember(Value:="Syli")> GNS
    <EnumMember(Value:="Ekwele")> GQE
    <EnumMember(Value:="Drachma")> GRD
    <EnumMember(Value:="Quetzal (Guatemala)")> GTQ
    <EnumMember(Value:="Guinea-Bissau Peso")> GWP
    <EnumMember(Value:="Guyana Dollar")> GYD
    <EnumMember(Value:="Hong Kong Dollar")> HKD
    <EnumMember(Value:="Lempira (Honduras)")> HNL
    <EnumMember(Value:="Croatian Kuna")> HRK
    <EnumMember(Value:="Gourde (Haiti)")> HTG
    <EnumMember(Value:="Forint (Hungary)")> HUF
    <EnumMember(Value:="Rupiah (Indonesia)")> IDR
    <EnumMember(Value:="Irish Pound")> IEP
    <EnumMember(Value:="New Israeli Shekel")> ILS
    <EnumMember(Value:="Indian Rupee")> INR
    <EnumMember(Value:="Iraqi Dinar")> IQD
    <EnumMember(Value:="Iranian Rial")> IRR
    <EnumMember(Value:="Iceland Krona")> ISK
    <EnumMember(Value:="Lira")> ITL
    <EnumMember(Value:="Jamaican Dollar")> JMD
    <EnumMember(Value:="Jordanian Dinar")> JOD
    <EnumMember(Value:="Yen (Japan)")> JPY
    <EnumMember(Value:="Kenyan Shilling")> KES
    <EnumMember(Value:="Som (Kyrgyzstan)")> KGS
    <EnumMember(Value:="Riel (Cambodia)")> KHR
    <EnumMember(Value:="Comorian Franc")> KMF
    <EnumMember(Value:="North Korean Won")> KPW
    <EnumMember(Value:="Won (South Korea)")> KRW
    <EnumMember(Value:="Kuwaiti Dinar")> KWD
    <EnumMember(Value:="Cayman Islands Dollar")> KYD
    <EnumMember(Value:="Tenge (Kazakstan)")> KZT
    <EnumMember(Value:="Lao Kip")> LAK
    <EnumMember(Value:="Lebanese Pound")> LBP
    <EnumMember(Value:="Sri Lankan Rupee")> LKR
    <EnumMember(Value:="Liberian Dollar")> LRD
    <EnumMember(Value:="Loti (Lesotho)")> LSL
    <EnumMember(Value:="Maloti")> LSM
    <EnumMember(Value:="Lithuanian Litas")> LTL
    <EnumMember(Value:="Luxembourg Franc")> LUF
    <EnumMember(Value:="Latvian Lat")> LVL
    <EnumMember(Value:="Libyan Dinar")> LYD
    <EnumMember(Value:="Moroccan Dirham")> MAD
    <EnumMember(Value:="Moldovan Leu")> MDL
    <EnumMember(Value:="Malagasy Ariary (Madagascar)")> MGA
    <EnumMember(Value:="Malagasy Franc")> MGF
    <EnumMember(Value:="Denar (Macedonia)")> MKD
    <EnumMember(Value:="Mali Franc")> MLF
    <EnumMember(Value:="Kyat (Myanmar)")> MMK
    <EnumMember(Value:="Tugrik (Mongolia)")> MNT
    <EnumMember(Value:="Pataca (Macau)")> MOP
    <EnumMember(Value:="Ouguiya (Mauritania)")> MRO
    <EnumMember(Value:="Ouguiya")> MRU
    <EnumMember(Value:="Maltese Lira")> MTL
    <EnumMember(Value:="Maltese Pound")> MTP
    <EnumMember(Value:="Mauritian Rupee")> MUR
    <EnumMember(Value:="Rufiyaa (Maldives)")> MVR
    <EnumMember(Value:="Malawi Kwacha")> MWK
    <EnumMember(Value:="Mexcian Peso")> MXN
    <EnumMember(Value:="Mexican Peso")> MXP
    <EnumMember(Value:="Mexican Unidad de Inversion")> MXV
    <EnumMember(Value:="Malaysian Ringgit")> MYR
    <EnumMember(Value:="Metical (Mosambique)")> MZM
    <EnumMember(Value:="Metical (Mozambique)")> MZN
    <EnumMember(Value:="Namibian Dollar")> NAD
    <EnumMember(Value:="Naira (Nigeria)")> NGN
    <EnumMember(Value:="Cordoba")> NIC
    <EnumMember(Value:="Cordoba Oro")> NIO
    <EnumMember(Value:="Netherlands Guilder")> NLG
    <EnumMember(Value:="Norwegian Krone")> NOK
    <EnumMember(Value:="Nepalese Rupee")> NPR
    <EnumMember(Value:="New Zealand Dollar")> NZD
    <EnumMember(Value:="Omani Rial")> OMR
    <EnumMember(Value:="Balboa (Panama)")> PAB
    <EnumMember(Value:="Sol")> PEN
    <EnumMember(Value:="Sol")> PES
    <EnumMember(Value:="Kina (Papua New Guinea)")> PGK
    <EnumMember(Value:="Philippine Peso")> PHP
    <EnumMember(Value:="Pakistan Rupee")> PKR
    <EnumMember(Value:="Zloty (Poland)")> PLN
    <EnumMember(Value:="Zloty")> PLZ
    <EnumMember(Value:="Portugese Escudo")> PTE
    <EnumMember(Value:="Guarani (Paraguay)")> PYG
    <EnumMember(Value:="Qatari Rial")> QAR
    <EnumMember(Value:="Old Leu (Romania)")> ROL
    <EnumMember(Value:="New Leu (Romania)")> RON
    <EnumMember(Value:="Serbian Dinar")> RSD
    <EnumMember(Value:="Russian Ruble")> RUB
    <EnumMember(Value:="Russian Ruble")> RUR
    <EnumMember(Value:="Rwandan Franc")> RWF
    <EnumMember(Value:="Saudi Riyal")> SAR
    <EnumMember(Value:="Solomon Islands Dollar")> SBD
    <EnumMember(Value:="Luigino")> SBL
    <EnumMember(Value:="Seychelles Rupee")> SCR
    <EnumMember(Value:="Sudanese Dinar")> SDD
    <EnumMember(Value:="Sudanese Pound")> SDG
    <EnumMember(Value:="Sudanese Pound")> SDP
    <EnumMember(Value:="Swedish Krona")> SEK
    <EnumMember(Value:="Singapore Dollar")> SGD
    <EnumMember(Value:="Saint Helena Pound")> SHP
    <EnumMember(Value:="Tolar (Slovenia)")> SIT
    <EnumMember(Value:="Slovak Koruna")> SKK
    <EnumMember(Value:="Leone (Sierra Leone)")> SLE
    <EnumMember(Value:="Leone (Sierra Leone)")> SLL
    <EnumMember(Value:="Somalian Shilling")> SOS
    <EnumMember(Value:="Surinam Dollar")> SRD
    <EnumMember(Value:="Suriname Guilder")> SRG
    <EnumMember(Value:="South Sudanese Pound")> SSP
    <EnumMember(Value:="Dobra (Sao Tome and Principa)")> STD
    <EnumMember(Value:="Dobra")> STN
    <EnumMember(Value:="Ruble")> SUR
    <EnumMember(Value:="El Salvador Colon")> SVC
    <EnumMember(Value:="Syrian Pound")> SYP
    <EnumMember(Value:="Lilangeni (Swaziland)")> SZL
    <EnumMember(Value:="Baht (Thailand)")> THB
    <EnumMember(Value:="Tajik Ruble")> TJR
    <EnumMember(Value:="Somoni (Tajikistan)")> TJS
    <EnumMember(Value:="Manat (Turkmenistan)")> TMM
    <EnumMember(Value:="Manat (Turkmenistan)")> TMT
    <EnumMember(Value:="Tunisian Dinar")> TND
    <EnumMember(Value:="Pa'anga (Tonga)")> TOP
    <EnumMember(Value:="Timor Escudo")> TPE
    <EnumMember(Value:="Old Turkish Lira")> TRL
    <EnumMember(Value:="New Turkish Lira")> TRY
    <EnumMember(Value:="Trinidad and Tobago Dollar")> TTD
    <EnumMember(Value:="New Taiwan Dollar")> TWD
    <EnumMember(Value:="Tanzanian Shilling")> TZS
    <EnumMember(Value:="Hryvnia (Ukraine)")> UAH
    <EnumMember(Value:="Uganda Shilling")> UGS
    <EnumMember(Value:="Uganda Shilling")> UGX
    <EnumMember(Value:="United States Dollar, next day")> USN
    <EnumMember(Value:="US Dollar (same day)")> USS
    <EnumMember(Value:="Uruguay Peso en Unidades Indexadas")> UYI
    <EnumMember(Value:="Uruguayan Peso")> UYP
    <EnumMember(Value:="Uruguayan Peso")> UYU
    <EnumMember(Value:="Unidad Previsional")> UYW
    <EnumMember(Value:="Som (Uzbekistan)")> UZS
    <EnumMember(Value:="Bolivar (Venezuela)")> VEB
    <EnumMember(Value:="Bolívar")> VEF
    <EnumMember(Value:="Bolívar Soberano")> VES
    <EnumMember(Value:="Dong (Vietnam)")> VND
    <EnumMember(Value:="Vatu (Vanuatu)")> VUV
    <EnumMember(Value:="Tala (Samoa)")> WST
    <EnumMember(Value:="CFA Franc BEAC")> XAF
    <EnumMember(Value:="Silver (in ounces)")> XAG
    <EnumMember(Value:="Gold (in ounces)")> XAU
    <EnumMember(Value:="European Composite Unit (EURCO)")> XBA
    <EnumMember(Value:="European Monetary Unit (E.M.U. - 6)")> XBB
    <EnumMember(Value:="European Unit of Account 9 (E.U.A. - 9)")> XBC
    <EnumMember(Value:="European Unit of Account 17")> XBD
    <EnumMember(Value:="Bitcoin")> XBT
    <EnumMember(Value:="East Caribbean Dollar")> XCD
    <EnumMember(Value:="Special Drawing Rights (IMF)")> XDR
    <EnumMember(Value:="European Currency Unit")> XEU
    <EnumMember(Value:="Gold-Franc (Special Settlement Currency)")> XFO
    <EnumMember(Value:="UIC-Franc (Special Settlement Currency)")> XFU
    <EnumMember(Value:="CFA Franc BCEAO")> XOF
    <EnumMember(Value:="Palladium (in ounces)")> XPD
    <EnumMember(Value:="CFP Franc (French Polynesia)")> XPF
    <EnumMember(Value:="Platinum (in ounces)")> XPT
    <EnumMember(Value:="SUCRE")> XSU
    <EnumMember(Value:="No currency code")> XXX
    <EnumMember(Value:="Yemeni Dinar")> YDD
    <EnumMember(Value:="Yemeni Rial")> YER
    <EnumMember(Value:="Yugoslavian Dinar")> YUD
    <EnumMember(Value:="New Dinar")> YUM
    <EnumMember(Value:="Yugoslav New Dinar")> YUN
    <EnumMember(Value:="Rand (financial)")> ZAL
    <EnumMember(Value:="Rand (Lesotho, Namibia, South Africa)")> ZAR
    <EnumMember(Value:="Kwacha (Zambia)")> ZMK
    <EnumMember(Value:="Kwacha (Zambia)")> ZMW
    <EnumMember(Value:="Zimbabwe Dollar")> ZWD
    <EnumMember(Value:="Zimbabwe Dollar")> ZWL
    <EnumMember(Value:="Unknown")> ZZZ
End Enum
